-- phpMyAdmin SQL Dump
-- version 4.0.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 03, 2014 at 09:12 PM
-- Server version: 5.6.12-log
-- PHP Version: 5.4.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `automobili`
--
CREATE DATABASE IF NOT EXISTS `automobili` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `automobili`;

-- --------------------------------------------------------

--
-- Table structure for table `komentar`
--

CREATE TABLE IF NOT EXISTS `komentar` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ime` varchar(100) NOT NULL,
  `komentar` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=19 ;

--
-- Dumping data for table `komentar`
--

INSERT INTO `komentar` (`id`, `ime`, `komentar`) VALUES
(18, 'sdf', 'sd');

-- --------------------------------------------------------

--
-- Table structure for table `modeli`
--

CREATE TABLE IF NOT EXISTS `modeli` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `marka` int(11) NOT NULL,
  `nazivModela` varchar(100) NOT NULL,
  `slika` varchar(100) NOT NULL,
  `specifikacije` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=22 ;

--
-- Dumping data for table `modeli`
--

INSERT INTO `modeli` (`id`, `marka`, `nazivModela`, `slika`, `specifikacije`) VALUES
(6, 3, 'BMW 5', 'bmw520i.jpg', '&#352;esta generacija, model F10/11, se proizvodi od 2010. godine. Kao i prethodne i ova je generacija bazirana na modificiranoj platformi serije 7. Novi model je ve&#263;i i dizajnerski druga&#269;iji od prethodnika. Spoljna svietla su opet u obliku slova L, unutra&#353;njost je sli&#269;na seriji 7 a napred dominiraju, kao u seriji 7, veliki bubrezi.\r\nTehnologija i motori su kao i sve ostalo preuzeti sa serije 7.'),
(7, 3, 'BMW 3', 'slika3.jpg', 'Serija 3 BMW-a je svojevrsna institucija modernog automobilizma. Tokom trideset godina proizvodnje i &#269;etiri nadprose&#269;no uspe&#353;ne evolucije, ovaj model ima posebno mesto u nomenklaturi svetske automobilske industrije. Konkretno, Serija 3 je najva&#382;niji i globalno najprodavaniji model kompanije BMW. Pored toga, ova automobilska dinastija je i formirala poznati imid&#382; brenda koji je i najprepoznatljiviji ba&#353; na ovom modelu. \r\n'),
(8, 1, 'Alfa Romeo Giulietta', 'giullieta.jpg', 'Testirana Giulietta je imala 2.0 l JTDM dizel motor sa 170 KS i 350 Nm obrtnog momenta. Prema fabri&#269;kim podacima maksimalna brzina Giuliette sa ovim motorom iznosi 217 km/h, a od 0 do 100 km/h ubrzava za 8.0 sekundi. Motor je uparen sa &#353;estostepenim manuelnim menja&#269;em. Prose&#269;na kombinovana potro&#353;nja je deklarisana na 4.7 l na 100 km. Na na&#353;em testu prose&#269;na potro&#353;nja je iznosila 8 litara na 100 km. '),
(9, 9, 'FIAT 500L', 'fiat.jpg', 'Motor je provereni, pouzdani 1,3-litarski Multijet sa dve bregaste osovine i 85 KS pri 3.500 obrtaja radilice. Posti&#382;e najve&#263;i obrtni moment od 200 Nm pri 2.000 o./min. U kombinaciji sa pestostepenim ru&#269;nim menja&#269;em prili&#269;no dugih hodova, novi Fiat 500L sa ovim motorom posti&#382;e najve&#263;u brzinu od 165 km/h, &#269;ak i sa zimskim pneumaticima, a do "stotke" ubrzava za 15 sekundi. Prose&#269;na potro&#353;nja goriva na testu iznela je 5,9 litara, iako je auto vo&#382;en i po snegu. Fabrika deklari&#353;e prose&#269;nu potro&#353;nju od samo 4,2 l/100, &#353;to nije mogu&#263;e ostvariti. Iako na momente po&#382;elite sna&#382;niji motor, uvek vam je na raspolaganju pristojna koli&#269;ina obrtnog momenta, pa su i me&#273;uubrzanja bolja nego kod benzinca, a sve to iz manje buke i naprezanja. upotpunjuje paletu motora. Cena Fiata 500L je sada toliko konkurentna da najnoviji model u ovoj klasi, Ford-B Max, ali i Opel Meriva, sa sli&#269;nom opremom ko&#353;taju vi&#353;e od Fiata 500L. Fiat 500L je mnogo prostraniji od kompletne konkurencije. Ford B-Max, koji nam dolazi iz kom&#353;iluka, nudi putnicima napred 7,5 cm, a pozadi &#269;ak 9 cm manje prostora za laktove nego "na&#353;" Fiat 500L. '),
(10, 17, 'Mazda CX-5', 'mazdaCX.jpg', 'Ba&#353; zato je izgled CX-5 sve&#382;, bez elemenata pozajmljenih sa drugih Mazdinih modela, potpuno jedinstven. Ono &#353;to &#263;e vam prvo upasti u o&#269;i je neobi&#269;an izgled za&#353;titne maske hladnjaka, koja je izba&#269;ena napred pa u izvesnoj meri podse&#263;a na branik. Sama maska zajedno sa farovima podse&#263;a na lice geparda, &#353;to nije nimalo slu&#269;ajna asocijacija Mazdinih dizajnera, jer je re&#269; o najbr&#382;oj kopnenoj &#382;ivotinji.\r\nLinije automobila, koje se uzdi&#382;u ka zadnjem delu, CX-5 daju izgled "grabljivca" u pokretu, a takav &#263;e utisak i ostaviti kada ga drugi voza&#269;i ugledaju u retrovizoru.\r\n \r\nUtisak koji &#263;e enterijer ostaviti na vas zavisi od toga na koja &#263;ete vrata u&#263;i. Ukoliko u&#273;ete na suvoza&#269;eva vrata, ima&#263;e i vi&#353;e nego dovoljno prostora za noge, a i prili&#269;no udobno &#263;ete se zavaliti u svom sedi&#353;tu. Kvalitet materijala kojim su sedi&#353;ta presvu&#269;ena (makar u slu&#269;aju paketa opreme automobila koji smo mi vozili) je sasvim prose&#269;an.'),
(11, 13, 'Jeep Grand Cherokee', 'jeep.jpg', 'Dizajnere Jeep-a &#263;emo ovde izgrditi, jer koli&#269;ina promena na zadnjem delu navodi na pomisao da svi radovi na Compassu nisu zavr&#353;eni. Jednostavno, izgleda kao da su na zadnjem delu stali, jer osim malog spojlera, ovde nema &#353;ta izdvojiti.\r\n \r\n&#352;to se ti&#269;e enterijera, tu je napredak u odnosu na prethodnu generaciju o&#269;igledan. Enterijer odgovara premijum krosover klasi u kojoj se Compass nalazi a visok kvalitet materijala, hromirane elemente, ko&#382;na sedi&#353;ta daju poseban ugo&#273;aj u vo&#382;nji.\r\n \r\nProstora ima dovoljno i sedi&#353;ta su uprkos izra&#382;enim bo&#269;nim osloncima za telo dosta komotna, pa i voza&#269; i preostala &#269;etiri putnika u&#382;ivaju u ponu&#273;enom komforu. Polo&#382;aj za upravlja&#269;em, raspored komandi i preglednost su sasvim dobro prilago&#273;eni voza&#269;u.\r\n \r\nPri dizajniranju naslona za ruku vodilo se ra&#269;una da bude prilagodljiv razli&#269;itim voza&#269;ima tako da je napravljen kao klizni naslon za ruku koji se mo&#382;e pomeriti do 7 cm napred.'),
(12, 9, 'Fiat Punto Classic', 'fiatPunto.jpg', 'Punto Classic TNG dolazi samo sa Dynamic, srednjim paketom opreme, koji uklju&#269;uje vazdu&#353;ne jastuke za voza&#269;a i suvoza&#269;a, centralnu bravu, putni ra&#269;unar, metalik boju i klima ure&#273;aj.\r\n \r\nOno &#353;to Dynamic paket ne donosi je ABS, koji nije mogu&#263;e dobiti ni uz doplatu. Sa druge strane, uz doplatu mo&#382;ete dobiti naslone za zadnja sedi&#353;ta, kojih nema u okviru samog paketa.\r\n \r\nInteresantan detalj u opremi predstavlja "city servo", koji pru&#382;a poseban ugo&#273;aj u gradskoj vo&#382;nji. U "city servo" modu, upravlja&#269; pru&#382;a manji otpor pri okretanju, pa je 3.9 metara duga&#269;ak automobil jo&#353; lak&#353;i za manevrisanje. Na otvorenom putu, preporu&#269;ljivo je isklju&#269;iti ovu opciju, pa upravlja&#269; postaje primereniji takvom vidu vo&#382;nje.\r\n \r\nGlavna karakteristika ovog automobila nije njegov spolja&#353;nji izgled niti njegova unutra&#353;njost, ve&#263; &#269;injenica da je prvi model koji na tr&#382;i&#353;te dolazi sa fabri&#269;ki ugra&#273;enom plinskim ure&#273;ajem. Pored toga re&#269; o novom automobilu, koji nudi malu potro&#353;nju - osobina koji kupci u Srbiji i te kako znaju da cene.\r\n '),
(13, 12, 'Hyundai', 'hyuindai.jpg', 'Hyundai ix20 je dizajnerski i tehni&#269;ki razvijen u Evropi. Na prvi pogled isti&#269;e se &#353;estougaona maska motora, ali i &#269;vrst, mi&#353;i&#263;av izgled koji karakteri&#353;e velika doza individualnosti. Bo&#269;ni pokaziva&#269;i smera su integrisani na retrovizorima, dok su zadnja svetla visoko postavljena i dobro vidljiva ostalim u&#269;esnicima u saobra&#263;aju. Stil ix20 je u skladu sa novim na&#269;inom izra&#382;avanja korejske kompanije, koja &#382;eli da se pozicionira na evropskom tr&#382;i&#353;tu kao moderan i progresivan brend. Nakon modela i20, ovo je drugi automobil koji prati novi "fluidni" dizajn - koji polako postaje glavni vizuelni element Hyundaija u Evropi.\r\n\r\nZa dizajn ix20 zaslu&#382;ni su dizajneri Hyundai Centra u nema&#269;kom Ruselhajmu i njihov dizajnerski potpis nosi &#269;etiri glavna elementa: dinami&#269;nost, sofisticiranost, eleganciju i samouverenost.\r\n\r\nAko bi trebalo jednom re&#269;ju da opi&#353;emo ix20, dovoljno bi bilo re&#263;i "prakti&#269;nost". Unutra&#353;njost je vrlo prostrana pogotovo kada je re&#269; o zadnjem sedi&#353;tu koje se mo&#382;e lako podesiti i pove&#263;ati prostor za putnike ili pove&#263;ati zapreminu prtlja&#382;nika. Ovde treba pomenuti da je prtlja&#382;nik ix20 znatno ve&#263;i od prtlja&#382;nika modela i30, sa maksimalnom zapreminom od 1,486 litara.'),
(14, 7, 'Dacia Duster', '', 'Duster je duga&#269;ak 4.31, &#353;irok 1.82 i visok 1.63 metara, ima oja&#269;anu &#353;asiju koja je od tla udaljena 210 mm i prilago&#273;ena je kori&#353;&#263;enju na razli&#269;itim podlogama i terenima. U Dusteru mogu udobno da se smeste pet odraslih putnika, a zapremina prtlja&#382;nika se sa osnovnih 475 l, preklapanjem zadnjih sedi&#353;ta, mo&#382;e pove&#263;ati na 1636 l.\r\n\r\nRazvijen je na platformi preuzetoj od Logana sa prednjim ogibljenjem tipa McPherson. Zadnje ogibljenje se razlikuje u zavisnosti od verzije. Kod verzije 4x4 ono je multi-link, dok je kod verzije 4x2 polukruta osovina, tako da su to u osnovi dva razli&#269;ita automobila.\r\n'),
(15, 11, 'Honda CR-Z', 'hondaCRZ.JPG', 'Atraktivni sportski oblik karoserije ukazuje na izuzetno dobru aerodinamiku &#353;to potvr&#273;uje i koeficijent otpora vazduha od 0.25. Automobil je duga&#269;ak 4.07 m, &#353;irok 2.01 m i visok 1.39 m. Me&#273;uosovinsko rastojanje od 2425 mm omogu&#263;ava prili&#269;no dobru okretnost automobila.\r\nHonda CR-Z je opremljena hibridnim IMA (Integrated Motor Assist) sistemom koji uskla&#273;uje rad benzinskog i elektromotora. Osnovni motor je benzinski, zapremine 1496 ccm sa 114 KS. Poma&#382;e mu elektromotor, sme&#353;ten izme&#273;u benzinskog motora i menja&#269;a, koji po potrebi omogu&#263;ava pove&#263;anje snage motora. Benzinski motor kombinovan sa snagom i obrtnim momentom elektromotora, daje ukupnu snagu od 124 KS i ukupan obrtni momenat od 174 Nm. Hibridni IMA sistem u elektromotornoj funkciji radi kao dodatni pogonski agregat, a u funkciji generatora proizvodi struju kojom puni akumulator. Pored toga ima i funkciju elektronskog prigu&#353;iva&#269;a vibracija benzinskog motora. Potrebna energija za napajanje hibridnog IMA sistema skladi&#353;ti se u nikl-metal-hidridnim baterijama te&#382;ine 75 kg i ukupnog napona 101 V.'),
(16, 5, 'Chevrolet Spark', 'chevroletSpark.jpg', 'Uprkos malim dimenzijama, Spark je dovoljno veliki da preveze &#269;etiri odrasle osobe. Na prednjim sedi&#353;tima mesta za voza&#269;a i suvoza&#269;a ima sasvim dovoljno i tokom vo&#382;nje ne dolazi do me&#273;usobnog dodirivanja. Na zadnjim sedi&#353;tima komotno mogu da sede dve odrasle osobe. Prtlja&#382;nik je ne&#353;to skromnijih dimenzija i njegova zapremina iznosi 170 l, a preklapanjem naslona zadnjih sedi&#353;ta mo&#382;e se uve&#263;ati na maksimalnih 568 l.\r\nTestirani Chevrolet Spark je imao &#269;etvorocilindri&#269;ni benzinski DOHC motor 1.0 l 16V sa 68 KS i 93 Nm obrtnog momenta pri 4.800 o/min. Prema fabri&#269;kim podacima maksimalna brzina Sparka sa ovim motorom iznosi 154 km/h, a prose&#269;na potro&#353;nja 5.1 l/100 km. Prose&#269;na potro&#353;nja na na&#353;em testu je iznosila 5.7 l/100km. Ako se uzme u obzir da je vo&#382;nja bila &#382;ustrija, ovaj rezultat prose&#269;ne potro&#353;nje je za svaku pohvalu. Spark se sa ovim motorom lepo snalazi po gradu. Ubrzanja izme&#273;u semafora su prili&#269;no ubedljiva, a po&#353;to se maksimalni obrtni moment posti&#382;e na prili&#269;no visokom broju obrtaja, auto tra&#382;i ja&#269;i gas. Motor ima veoma ugla&#273;en rad i na ni&#382;im i na vi&#353;im obrtajima. Uop&#353;te nije bu&#269;an, a kada radi na leru prakti&#269;no se i ne&#269;uje. Za to je naravno veoma zaslu&#382;na i izolacija koja je na ovom modelu prili&#269;no dobro ura&#273;ena. Motor je uparen sa petostepenim menja&#269;em ne&#353;to du&#382;ih hodova. Pored toga &#353;to preciznost nije na njegovoj strani, menja&#269; svoj posao korektno obavlja.'),
(17, 14, 'Kia Venge', 'kiaVenga.jpg', 'Svojim oblikom i du&#382;inom od 4.068 mm pripada kategoriji kompaktnih monovolumena "B" segmenta. Dinami&#269;an i sportski izgled Venge potvr&#273;uje i koeficijent otpora vazduha od 0.31 koji je najni&#382;i u klasi.\r\nVenga je dizajnerski i tehni&#269;ki razvijena u Evropi. Na prvi pogled isti&#269;e se ’nasmejana’ maska motora, ali i &#269;vrst, mi&#353;i&#263;av izgled koji karakteri&#353;e velika doza individualnosti. Prednji farovi atraktivno o&#353;trog dizajna imaju integrisane pokaziva&#269;e smera, dok su zadnja svetla visoko postavljena i dobro vidljiva ostalim u&#269;esnicima u saobra&#263;aju. Elegantna bo&#269;na silueta, udubljenje na donjem rubu karoserije, linija prozora koja se podi&#382;e ka zadnjem delu, ravni krov i atraktivan zadnji deo zajedno doprinose dobrom izgledu.\r\nUnutra&#353;njost Venge je, s obzirom na segment kom pripada, veoma prostrana. Ima mesta za pet odraslih putnika pri &#269;emu &#263;e se &#269;etiri putnika ose&#263;ati veoma komotno. Sedi&#353;ta su prili&#269;no udobna i izdignuta tako da je pozicija sedenja ne&#353;to vi&#353;a nego kod konkurentnih modela. Usled povi&#353;enog polo&#382;aja sedenja mesta za kolena ima i na pretek. Ovakav polo&#382;aj sedenja obezbe&#273;uje voza&#269;u dobru preglednost kako ispred tako i iza automobila.'),
(18, 10, 'Ford Fiesta', 'fordFiesta.jpg', 'Ford Fiesta se na tr&#382;i&#353;tu automobila pojavila jo&#353; davnih 70-ih godina pro&#353;log veka i tada je bila Fordov predstavnik u segmentu malih automobila. Taj segment tada nije bio ba&#353; toliko popularan ali danas je segment koji je zastupljen modelima svih proizvo&#273;a&#269;a. Za uspe&#353;an nastup u ovom tr&#382;i&#353;nom segmentu nije od presudnog zna&#269;aja ni dizajn, ni sna&#382;an motor, ni broj zvezdica na crash testovima ve&#263; uspe&#353;an spoj svega navedenog uz pristupa&#269;nu cenu i ekonomi&#269;an motor.\r\nJedan od glavnih aduta Ford Fieste je sigurno njen dizajn. Nekada&#353;nji konzervativan dizajn zamenjen je aktuelnim Fordovim dizajnom, inspirisanim novim "Kinetic" Focusom, koji podjednako dobro pristaje kako Focusu i Mondeu tako i kompaktnoj Fiesti. Odlu&#269;an i agresivan oblik nove Fieste od po&#269;etka govori da Fiesta nije &#382;elela igrati sporedne uloge i biti jo&#353; jedan od modela u Fordovoj ponudi ve&#263; ne&#353;to vi&#353;e od toga.'),
(19, 17, 'Mazda 6', 'mazda6.jpg', 'Kako bismo bolje razumeli "zoom-zoom" pojam moramo da shvatimo koncept "kizuna". Kizuna je zapravo ose&#263;aj kod voza&#269;a i to onaj koji nastaje savr&#353;enim uklapanjem performansi, udobnosti, poverenja, stila i po&#382;eljnosti &#269;ime se stvara duboka emotivna povezanost izme&#273;u voza&#269;a i automobila. "zoom-zoom" je dizajn inspirisan sportom i uro&#273;enom potrebom za kretanjem a u su&#353;tini govori kako je svaki deo Mazde dizajniran i razvijan tako da jasno prati postavljen razvojni cilj, a to je da omogu&#263;i voza&#269;ima da u potpunosti do&#382;ive ose&#263;aj "kizune".\r\nNova Mazda6 je dostupna u tri karoserijske verzije, kao sedan, hatchback i karavan. Redizajniranjem prednjih i zadnjih svetlosnih grupa kao i svetala za maglu, koja su sada okrugla i sme&#353;tena u samim uglovima prednjeg spojlera, nova Mazda6 je dobila dodatno nagla&#353;en sportski izgled. Osim toga, posebnim redizajnom prednje maske i farova dizajneri su postigli karakteristi&#269;an izgled nasmejanog automobila. Dostupno je deset razli&#269;itih boja karoserije, od &#269;ega su dve potpuno nove.\r\nNova Mazda6 je duga&#269;ka 4.755 mm, &#353;iroka 1.795 mm i visoka 1.440 mm. Me&#273;uosovinsko rastojanje iznosi 2.725 mm. Masa praznog vozila je 1.435 kg.'),
(20, 6, 'Citroen C3', 'citroenC3.jpg', 'Citroen je oduvek te&#382;io ekstravaganciji i nekonvencionalnom dizajnu &#353;to dokazuje svakim novim modelom. Iako je dizajn modela C3 logi&#269;an nastavak Citroenove originalne ideje, novi C3 je zadr&#382;ao sve kvalitete prethodnika, oti&#353;ao nekoliko koraka dalje i sada izgleda &#269;vr&#353;&#263;e, ozbiljnije i kvalitetnije.\r\nNovi Citroen C3 je dizajniran tako da privla&#269;i pa&#382;nju kako mu&#353;kih tako i &#382;enskih voza&#269;a. Proizvodi se isklju&#269;ivo sa petoro vrata dok sa troje vrata dolazi ekskluzivnija verzija DS3.\r\nPrednjim delom novog C3 modela dominiraju veliki farovi, velika maska hladnjaka prese&#269;ena malim branikom na kome se nalazi nosa&#269; registarske tablice i svetla za maglu. Na zadnjoj strani automobila uo&#269;avamo velike zadnje svetlosne grupe koje svojim oblikom podse&#263;aju na boomerang.\r\nNa na&#353;em tr&#382;i&#353;tu C3 &#263;e biti dostupan sa ukupno sedam verzija motora. U ponudi &#263;e biti tri verzije dizel HDI motora od 70, 90 i 110 KW i &#269;etiri benzinska 1.1, 1.4, Vti 95 i Vti 120 koji zadovoljavaju Euro 5 standard o izduvnim gasovima. Svi modeli motora imaju manuelne petostepene ili &#353;estostepene menja&#269;e, dok Vti 120 pru&#382;a mogu&#263;nost izbora menja&#269;a izme&#273;u manuelnog petostepenog ili &#269;etvorostepenog automatika.'),
(21, 1, '', '', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
